services:
  
  # 服务名
  ollama:
    # 模拟一个伪终端
    tty: true
    # 打开标准输入,可以接受外部输入
    stdin_open: true
    # 主机名
    hostname: ollama
    # 指定容器名称
    container_name: ollama
    # 指定为镜像名称或镜像ID
    image: danxiaonuo/ollama:latest
    # 覆盖容器启动后默认执行的命令
    # command: /sbin/init
    # 宿主机共享进程命名空间
    pid: host
    # 使用系统的IPC命名空间
    ipc: host
    # 允许容器中运行一些特权命令
    privileged: true
    # 指定容器退出后的重启策略为始终重启
    restart: always
    # 指定容器的内核能力(capacity)分配
    cap_add:
     - ALL
    # dns配置
    dns:
     - 8.8.8.8
     - 8.8.4.4
    # 数据卷所挂载路径设置
    volumes:
      # 数据目录
      - ./ollama:/root/.ollama:rw,cached
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
      # 共享内核
      - /sys/fs/bpf:/sys/fs/bpf:rw,cached
      - /lib/modules:/lib/modules:ro,cached
      - /etc/sysctl.conf:/etc/sysctl.conf:ro,cached
    # 环境变量
    environment:
      OLLAMA_HOST: 0.0.0.0
      OLLAMA_PORT: 11434
      OLLAMA_ORIGINS: "*"
      OLLAMA_NUM_PARALLEL: 16
      OLLAMA_MAX_LOADED_MODELS: 16
      OLLAMA_MODELS: /root/.ollama/models
      #HTTP_PROXY: http://127.0.0.1:7890
      #HTTPS_PROXY: http://127.0.0.1:7890
      #ALL_PROXY: http://127.0.0.1:7890
      #NO_PROXY: "localhost,127.0.0.1,0.0.0.0,ollama,.local"
      #no_proxy: "localhost,127.0.0.1,0.0.0.0,ollama,.local"
    # 指定设备映射关系
    devices:
     - /dev/net/tun
    # 解决容器的依赖
    #depends_on:
    #  - ""
    # 配置容器连接的网络
    networks:
      ollama_net:
    # 暴露端口信息
    ports:
    - "11434:11434"
    # 指定容器的 ulimits 限制值
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
 
  # 服务名
  openwebui:
    # 模拟一个伪终端
    tty: true
    # 打开标准输入,可以接受外部输入
    stdin_open: true
    # 主机名
    hostname: openwebui
    # 指定容器名称
    container_name: openwebui
    # 指定为镜像名称或镜像ID
    image: ghcr.io/open-webui/open-webui:main
    # 覆盖容器启动后默认执行的命令
    # command: /sbin/init
    # 宿主机共享进程命名空间
    pid: host
    # 使用系统的IPC命名空间
    ipc: host
    # 允许容器中运行一些特权命令
    privileged: true
    # 指定容器退出后的重启策略为始终重启
    restart: always
    # 指定容器的内核能力(capacity)分配
    cap_add:
     - ALL
    # dns配置
    dns:
     - 8.8.8.8
     - 8.8.4.4
    # 数据卷所挂载路径设置
    volumes:
      # 数据目录
      - ./open-webui:/app/backend/data:rw,cached
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
      # 共享内核
      - /sys/fs/bpf:/sys/fs/bpf:rw,cached
      - /lib/modules:/lib/modules:ro,cached
      - /etc/sysctl.conf:/etc/sysctl.conf:ro,cached
    # 环境变量
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_OPENAI_API: False
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: duckduckgo
      RAG_WEB_SEARCH_RESULT_COUNT: 5
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      #HTTP_PROXY: http://127.0.0.1:7890
      #HTTPS_PROXY: http://127.0.0.1:7890
      #ALL_PROXY: http://127.0.0.1:7890
      #NO_PROXY: "localhost,127.0.0.1,0.0.0.0,ollama,.local"
      #no_proxy: "localhost,127.0.0.1,0.0.0.0,ollama,.local"
    # 指定设备映射关系
    devices:
     - /dev/net/tun
    # 解决容器的依赖
    #depends_on:
    #  - ""
    # 配置容器连接的网络
    networks:
      ollama_net:
    # 暴露端口信息
    ports:
    - "80:8080"
    # 指定容器的 ulimits 限制值
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535


networks:
  ollama_net:
    driver: bridge
    enable_ipv6: false
    driver_opts:
      com.docker.network.bridge.name: ollama_net
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_forwarding: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.host_binding_ipv6: "::/0"
      com.docker.network.driver.mtu: 1500
    ipam:
      driver: default
      config:
      - subnet: 10.16.0.0/24
        gateway: 10.16.0.1
